PAYMENT_TERMS_ENUM = {"Net 15": "1", "Net 30": "2", "Due on receipt": "4"}
CURRENCY_ENUM = {"UAH": "6", "PLN": "7", "USD": "1"}
PAYMENT_METHOD_ENUM = {"ACH": "1", "Wire": "4", "Credit Card": "6"}
DEPARTMENT_ENUM = {
    "CX - Professional Services - COGS": "2",
    "HR - Shared": "6",
    "(OLD) G&A Ops": "7",
    "Marketing - Shared": "9",
    "Product - Shared": "12",
    "(OLD) Sales": "14",
    "CX - Engineering": "121",
    "Sales - Shared": "122",
    "CX - Enablement": "123",
    "Eng - Shared": "127",
    "CX - Shared": "128",
    "Balance Sheet": "130",
    "(OLD) GTM Leadership": "131",
    "Marketing - Acquisition": "132",
    "(OLD) Revenue Marketing": "133",
    "Marketing - Corporate": "134",
    "Sales - Account Executive": "135",
    "CX - Account Management": "136",
    "Sales - Development": "137",
    "CX - Customer Success": "138",
    "CX - Customer Support - COGS": "139",
    "Business Development": "140",
    "(OLD) R&D Leadership": "141",
    "Product - Ops": "142",
    "Marketing - Product": "143",
    "Product - Go Global": "144",
    "Product - Management": "145",
    "Product - UX": "146",
    "Eng - COGS": "148",
    "Executive": "149",
    "Corp Dev": "150",
    "HR - Talent Acquisition": "151",
    "HR - Business Partners": "152",
    "HR - People Operations": "153",
    "HR - Training & Enablement": "154",
    "HR - Facilities": "155",
    "F&O - Shared": "156",
    "Finance - Accounting": "157",
    "Finance - FP&A": "158",
    "RevOps": "159",
    "Data": "160",
    "IT & Security": "161",
    "Finance - Legal": "162",
    "F&O - COGS": "163",
    "Benefits": "164",
    "Non Operating": "331",
    "Revenue": "332",
    "Eng - Growth": "333",
    "Eng - Tailored Solutions": "334",
    "Eng - Application Services": "335",
    "Eng - Infrastructure": "336",
    "Eng - Solid Core": "337",
    "Eng - Agile": "339",
    "Eng - BizEng": "340",
    "Development Software Capitalization": "341",
    "Development Software Capitalization (COGS)": "342",
    "Eng - Incubation": "344",
    "Finance - Strategy Ops": "345",
    "Eng - Customer Value": "354",
    "Eng - Technology Hub": "355",
    "Eng - Application Platform": "356",
    "Eng - AI": "357",
    "Eng - Document App": "358",
}
CUSTOM_FORM_ENUM = {"PandaDoc United States- New Vendor Request Form": "45"}
CATEGORY_ENUM = {
    "Contractor": "1",
    "IT Services": "2",
    "Others": "3",
    "Transactional": "4",
}

PANDADOC_TO_NETSUITE_FIELD_IDS = {
    "Text1": "custrecord_company_name",
    "Text1_1_1": "custrecord_vr_email",
    "Text1_1_1_1": "custrecord_vr_website",
    "Text1_1": "custrecord1524",
    "Dropdown2": "custrecord_vr_payment_terms",
    "Text3": "custrecord1531",
    "Dropdown1": "custrecord_vr_pref_pymt_method",
    "Text2": "custrecord_vr_tax_id",
    "Checkbox1": "custrecord_vr_1099",
    "Dropdown4": "custrecord1530",
    "Dropdown3": "customform",
    "Dropdown5": "custrecord_vr_category",
    "Text5": "custrecord1553",
    "Text6": "custrecord_vr_notes",
}
